apiVersion: v1
kind: Service
metadata:
  name: kube-dns-metrics
  namespace: kube-system
  labels:
    metrics: kube-dns
    env: live
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 10055
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: kube-dns
