apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: kube-state-metrics
  namespace: prometheus
  labels:
    app: kube-state-metrics
    env: live
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
  - port: metrics
