apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: kube-state-metrics
  labels:
    k8s-app: kube-state-metrics
    env: live
spec:
  jobLabel: kube-state-metrics
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
  - port: metrics
