apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: kube-controller-manager
  labels:
    k8s-app: kube-controller-manager
    env: live
spec:
  jobLabel: kube-controller-manager
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      metrics: kube-controller-manager
  endpoints:
  - port: http-metrics
    interval: 15s
    scheme: http
