apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: kube-scheduler
  labels:
    k8s-app: kube-scheduler
    env: live
spec:
  jobLabel: kube-scheduler
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      metrics: kube-scheduler
  endpoints:
  - port: http-metrics
    interval: 30s
    scheme: http
