apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
    env: live
spec:
  jobLabel: kube-dns
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      metrics: kube-dns
  endpoints:
  - port: http-skydns-metrics
    interval: 60s
    scheme: http
  - port: http-dnsmasq-metrics
    interval: 60s
    scheme: http
