apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: node-exporter
  labels:
    k8s-app: node-exporter
    env: live
spec:
  jobLabel: node-exporter
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: metrics
