apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: main
  namespace: prometheus
  labels:
    prometheus: main
    app: prometheus
    env: live
spec:
  externalUrl: "https://${DEPLOY_PROMETHEUS_DOMAIN}"
  replicas: 1
  version: v1.5.2
  retention: 768h
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - {key: app, operator: In, values: [prometheus, node-exporter, kube-state-metrics, kube-dns]}
  alerting:
    alertmanagers:
    - namespace: prometheus
      name: alertmanager-main
      port: web
  resources:
    requests:
      memory: 400Mi
  storage:
    resources:
      requests:
        storage: 40Gi
