apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: main
  labels:
    prometheus: main
    app: prometheus
    env: live
spec:
  externalUrl: "https://${DEPLOY_PROMETHEUS_DOMAIN}"
  replicas: 1
  version: v1.5.2
  retention: 768h
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  alerting:
    alertmanagers:
    - namespace: ${DEPLOY_NAMESPACE}
      name: alertmanager-main
      port: web
  resources:
    requests:
      memory: 2Gi
  storage:
    resources:
      requests:
        storage: 40Gi
