apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
    env: live
spec:
  jobLabel: prometheus
  namespaceSelector:
    matchNames:
    - prometheus
  selector:
    matchLabels:
      app: prometheus
  endpoints:
  - port: web
    scheme: http
    interval: 60s
