apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  labels:
    metrics: kube-state-metrics
    app: kube-state-metrics
    env: live
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: kube-state-metrics
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
    env: live
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
        env: live
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: gcr.io/google_containers/kube-state-metrics:v0.4.1
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          requests:
            memory: 60Mi
            cpu: 100m
          limits:
            memory: 250Mi
            cpu: 200m
