apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager-metrics
  namespace: kube-system
  labels:
    k8s-app: kube-controller-manager
    metrics: kube-controller-manager
    env: live
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
    targetPort: 10252
  selector:
    k8s-app: kube-controller-manager
